### ISSUE TITLE
deploy_1.0.0 org.apache.ibatis.exceptions.TooManyResultsException issue

### ISSUE THREAD

**Issue by draken1** [draken1/telefield_server_m2m_7th#15]
```
org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:70)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at $Proxy12.findBySensorMacAndCallNumSensorAddr(Unknown Source)
	at com.telefield.server.m2m.bootstrap.M2MDAOBootstrap.sensorInfoUpdate(M2MDAOBootstrap.java:149)
	at com.telefield.server.m2m.socket.handler.service.impl.SensorPeriodicReportServiceImpl.sensor_info_update_and_periodic_report_save(SensorPeriodicReportServiceImpl.java:34)
	at com.telefield.server.m2m.socket.handler.M2MPacketProcessHandler.run(M2MPacketProcessHandler.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)

```

**Comment by draken1** [comment]
m2m -> 중앙서버로 메시지 전송시 소켓을 닫지않아 생겼던문제

현재는 소켓을닫음
